
POST http://localhost:9000/menus
Content-Type: application/json

{
  "title": "Arepa",
  "description": "Soup with some vegetables",
  "price": 1000,
  "state": true,
  "idCategory": 1
}

POST http://localhost:9000/category
Content-Type: application/json

{
  "name": "Starter"
}




PUT http://localhost:9000/users/3
Content-Type: application/json

{
  "name": "Naruto",
  "lastName": "Garcia",
  "identification": "12342322",
  "cellphone": 34211,
  "email": "Fernao@mail.com",
  "password": "************",
  "role": "ADMIN"
}


GET http://localhost:9000/users



POST http://localhost:9000/users
Content-Type: application/json

{
  "name": "Dani",
  "lastName": "Pe",
  "identification": "12342322",
  "cellphone": 34211,
  "email": "Fernao@mail.com",
  "password": "************",
  "role": "ADMIN"
}


